baseURL = "https://hoysu.github.io/2digit.github.io/"
languageCode = "en-us"
title = "2Digit"
# theme = "hugo-theme-pixyll-master"
theme = "hyde-master"
# theme = "hyde"
[params]
  themeColor = "theme-base-09"
